import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import NavigationMenu from "@/components/NavigationMenu";
import Header from "@/components/Header";
import { Toaster } from "@/components/toast/toaster";
import SessionManager from "./SessionManager";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-2/3 m-auto text-sm text-md flex flex-col bg-slate-300 h-full">
          <SessionManager>
            <div className="flex flex-col">
              <Header />
              <NavigationMenu />
            </div>
            <div className="flex flex-1 overflow-y-scroll flex-col">
              <main className="p-4">{children}</main>
              <Toaster />
            </div>
            <Footer />
          </SessionManager>
        </div>
      </body>
    </html>
  );
}
